### ISSUE TITLE
lots of npm deprecated warnings

### ISSUE THREAD

**Issue by quinton-ashley** [brackets-userland/brackets-npm-registry#46]
npm WARN deprecated babel-core@5.8.25: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated cross-spawn-async@1.0.1: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by zaggino** [comment]
Theres work being done directly in Brackets to make this registry not required anymore, so Im not planning on upgrading these unless something is broken.

**Comment by quinton-ashley** [comment]
Okay, everything is working fine.  Happy to hear that!  You make excellent plugins.

**Comment by zaggino** [comment]
Latest master branch (future 1.9 release) contains https://github.com/adobe/brackets/pull/10602 which makes this registry kind-of obsolete. I've already uploaded my extensions to the Brackets registry and will continue to publish updates to both registries,
